export const PERMISSIONS = [
    { id: 'dashboard.view', label: 'View Dashboard Statistics', category: 'General' },
    { id: 'patients.view', label: 'View Patient Directory', category: 'Patients' },
    { id: 'patients.create', label: 'Register New Patients', category: 'Patients' },
    { id: 'patients.edit', label: 'Update Patient Information', category: 'Patients' },
    { id: 'patients.delete', label: 'Delete Patient Records', category: 'Patients' },
    { id: 'orders.view', label: 'View Diagnostic Orders', category: 'Tests' },
    { id: 'orders.create', label: 'Place New Diagnostic Orders', category: 'Tests' },
    { id: 'orders.edit', label: 'Modify Existing Orders', category: 'Tests' },
    { id: 'orders.delete', label: 'Cancel/Delete Orders', category: 'Tests' },
    { id: 'samples.collect', label: 'Collect & Manage Specimens', category: 'Tests' },
    { id: 'results.enter', label: 'Enter Test Results', category: 'Tests' },
    { id: 'results.edit', label: 'Modify Entered Results', category: 'Tests' },
    { id: 'results.verify', label: 'Verify/Validate Results', category: 'Tests' },
    { id: 'results.delete', label: 'Delete Result Records', category: 'Tests' },
    { id: 'accounting.view', label: 'View Financial Reports', category: 'Financial' },
    { id: 'billing.manage', label: 'Manage Payments & Invoices', category: 'Financial' },
    { id: 'expenses.manage', label: 'Manage Lab Expenses', category: 'Financial' },
    { id: 'staff.manage', label: 'Manage Staff & Privileges', category: 'Administrative' },
    { id: 'lab.settings', label: 'Configure Lab Settings', category: 'Administrative' },
    { id: 'catalog.manage', label: 'Manage Test Catalog & Prices', category: 'Administrative' },
    { id: 'referrals.manage', label: 'Manage Referral Sources (Hospitals/Doctors)', category: 'Administrative' },
    { id: 'hmos.manage', label: 'Manage HMO Partners', category: 'Administrative' },
    { id: 'audit.view', label: 'View System Audit Logs', category: 'Administrative' },
];
